"""Initial tables

Revision ID: b14b0ce25349
Revises: 
Create Date: 2025-08-09 20:28:04.576027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14b0ce25349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poster', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
